### PR TITLE
Storyblok visual editor now works in both dev and preview env

### PR DESCRIPTION
**Pull request by dipankarmaikap**

### CODE REVIEW

**Comment by dipankarmaikap** [comment]
@Vuete Just modified the code a bit and it's working now as expected, There's no need to load storyblok multiple times.

**Comment by Vuete** [comment]
> @Vuete Just modified the code a bit and it's working now as expected, There's no need to load storyblok multiple times.

Thanks! It's working much better now and code is much cleaner without the load storyblok multiple times!

**Comment by Vuete** [comment]
> @Vuete Just modified the code a bit and it's working now as expected, There's no need to load storyblok multiple times.

@dipankarmaikap I did some more testing if you run `renderRichText()` client side in a function (for example behind a onClick$) it will say `Please initialize the Storyblok SDK before calling the renderRichText function` and renders nothing.

**Comment by dipankarmaikap** [comment]
@Vuete In this case, you have to load the storyblok again like my previous solution. However, I'm curious to understand why you need to rerun the `renderRichText` function based on a click event.

**Comment by Vuete** [comment]
> @Vuete In this case, you have to load the storyblok again like my previous solution. However, I'm curious to understand why you need to rerun the `renderRichText` function based on a click event.

@dipankarmaikap I have banner component with a list of text quotes. It renders the next quote every 2 seconds with an animation.

**Pull request merged**
